# Keybind

$terminal = alacritty
$fileManager = dolphin
$menu = wofi --show drun --no-actions --hide-scroll --insensitive
$browser = firefox
$steam = steam
$discord = discord

$mainMod = SUPER

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, W, killactive
bind = $mainMod, S, exec, $steam
bind = $mainMod, D, exec, $discord
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, T, togglefloating,
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, B, exec, $browser
bind = $mainMod, Escape, exec, hyprctl dispatch exit
bind = $mainMod CTRL, R, exec, hyprctl reload

# Focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move windows
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Resize windows
bind = $mainMod CTRL, H, resizeactive, -50 0
bind = $mainMod CTRL, L, resizeactive, 50 0
bind = $mainMod CTRL, K, resizeactive, 0 -50
bind = $mainMod CTRL, J, resizeactive, 0 50

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

